# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'myManagedCluster-devops'
    namespace: 'devops'
    command: 'delete'
    arguments: 'lightingsnakepipelinesjavascriptdocker'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'