apiVersion : apps/v1
kind: Deployment
metadata:
  name: lightingsnakepipelinesjavascriptdocker
  annotations:
    kubernetes.io/change-cause: "1.2.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightingsnakepipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: lightingsnakepipelinesjavascriptdocker 
    spec:
      containers:
        - name: lightingsnakepipelinesjavascriptdocker 
          image: myappcrandres.azurecr.io/lightingsnakepipelinesjavascriptdocker
          ports:
          - containerPort: 8080
